#!/bin/sh
# File: gallery.sh
#  Time-stamp: <2012-12-26 02:08:13 gawen>
#
#  Copyright (C) 2012 David Hauweele <david@hauweele.net>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.

set -- $(getopt "hVvOEe:t:n:q:C:T:c:R:" $*)

IMG_EXT="jpg jpeg png"

usage() (
    echo "$0 [OPTION...] <IMAGES>"
)

help() (
    usage
    echo " -h Show this help message."
    echo " -V Show the version."
    echo " -v Verbose mode"
    echo " -O Conserve original images."
    echo " -e Output images extension (default: jpg)."
    echo " -T Title (default: Gallery)."
    echo " -t Tiny size (default: '120x')."
    echo " -n Normal size (defualt: '800x')."
    echo " -q Reduce quality."
    echo " -c Stylesheet to use."
    echo " -C Extra convert arguments."
    echo " -R Resize the original images."
    echo " -E Add Exiv comments."
)

output=public_html
extension=jpg
tiny_size=x120
normal_size=x480
stylesheet=/usr/local/share/gallery/style.css
main_title="Gallery"
quality=80

while [ $1 != "--" ]
do
    case $1 in
        -h)
            help
            exit 0
            ;;
        -V)
            echo "Gallery v0.1 by David Hauweele <david@hauweele.net>"
            exit 0
            ;;
        -v) verbose=1;;
        -O) original=1;;
        -E) exiv=1;;
        -T) main_title=$2; shift;;
        -o) output=$2; shift;;
        -e) extension=$2; shift;;
        -q) quality=$2; shift;;
        -c) stylesheet=$2; shift;;
        -R) resize=$2; shift;;
        *)
            help
            exit 0
            ;;
    esac
    shift
done
shift

[ -r "$stylesheet" ] || { echo "Cannot read CSS stylesheet ($stylesheet)."; exit 1; }
convert -version >/dev/null 2>&1 || { echo "ImageMagick Convert Command-Line Tool required." >&2; exit 1; }
if [ -n "$exiv" ]
then
    exiv2 -V >/dev/null 2>&1 || { echo "EXIF/IPTC metadata manipulation tool required." >&2; exit 1; }
fi

if [ $# != 1 ]
then
    usage
fi

output_tiny="$output/tiny"
output_orig="$output/orig"
output_normal="$output/normal"

mkdir -p "$output"
mkdir -p "$output_normal"
mkdir -p "$output_tiny"
if [ -n "$original" ]
then
    mkdir -p "$output_orig"
fi

if [ -n "$quality" ]
then
    quality="-quality $quality"
fi

for ext in $IMG_EXT
do
    find_filter="$find_filter -iname \"*.$ext\" -o"
done
find_filter="$find_filter -false"

if [ -x "$(which par)" ]
then
    par="$(which par)"
    par_amp="&"
fi

if [ -x "$(which base)" -a -x "$(which crc32)" ]
then
    use_crcbase=1
fi

output_name() (
    if [ -n "$use_crcbase" ]
    then
        out=$(crc32 $1 | cut -d' ' -f 1 | base -O "0123456789abcdefghijklmnopqrstuvwxyz")
    else
        out=$(sha1sum $1)
    fi
    echo $out
)

exiv_field() (
    data=$(exiv2 -g $2 -Pt "$3")

    if [ -z "$data" -o "$data" = "Off" -o "$data" = "Not known" ]
    then
        exit 0
    fi

    echo "<tr>"
    echo "<td>$1</td>"
    echo "<td><i><b>$data</b></i></td>"
    echo "</tr>"
)

exiv_data() (
    echo "<div id=\"exif\" class=\"toggle\" onclick=\"toggle('exif', 'visible');toggle('exif_switch', 'hidden');\"><table>"
    exiv_field "Camera model" "Exif.Image.Model" "$1"
    exiv_field "Lens model" "Exif.CanonCs.LensType" "$1"
    exiv_field "Date" "Exif.Image.DateTime" "$1"
    exiv_field "Exposure" "Exif.Phto.ExposureTime" "$1"
    exiv_field "Aperture" "Exif.Photo.FNumber" "$1"
    exiv_field "Focal length" "Exif.Photo.FocalLength" "$1"
    exiv_field "ISO" "Exif.Photo.ISOSpeedRatings" "$1"
    exiv_field "Exposure bias" "Exif.Photo.ExposureBiasValue" "$1"
    exiv_field "Program" "Exif.Photo.ExposureProgram" "$1"
    exiv_field "Distance" "Exif.CanonSi.SubjectDistance" "$1"
    exiv_field "Timer" "Exif.CanonCs.SelfTimer" "$1"
    exiv_field "Metering" "Exif.CanonCs.Metering" "$1"
    exiv_field "Metering mode" "Exif.Image.MeteringMode" "$1"
    exiv_field "Flash mode" "Exif.CanonCs.FlashMode" "$1"
    exiv_field "Drive mode" "Exif.CanonCs.DriveMode" "$1"
    exiv_field "Focus mode" "Exif.CanonCs.FocusMode" "$1"
    exiv_field "YCbCr positioning" "Exif.Image.YCbCrPositioning" "$1"
    echo "</table></div>"
)

index="$output/index.html"
echo "<html>" > "$index"
echo "<head>" >> "$index"
echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">" >> "$index"
echo "  <link rel=\"shortcut icon\" type=\"image/png\" href=\"favicon.png\">" >> "$index"
echo "  <title>$main_title</title>" >> "$index"
echo "</head>" >> "$index"
echo "<body>" >> "$index"
echo "  <center>" >> "$index"
echo "  <h1>$main_title</h1>" >> "$index"
echo "  <div id=\"gallery\">" >> "$index"

tmp=$(tempfile)
for opt in $*
do
    files=$(eval find "$opt" $find_filter | xargs echo)
    for file in $files
    do
        out=$(output_name "$file")
        $par convert $quality -resize "$normal_size" "$file" "$output_normal/${out}_n.$extension" &
        $par convert $quality -resize "$tiny_size" "$file" "$output_tiny/${out}_t.$extension" &
        if [ -n "$original" ]
        then
            if [ -n "$resize" ]
            then
                $par convert $quality -resize "$resize" "$file" "$output_orig/${out}_o.$extension" &
            else
                # FIXME: Use original extension.
                cp "$file" "$output_orig/${out}_o.$extension"
            fi
        fi

        title=$(basename "$file")
        title=$(basename "$title" .$(echo "$title" | cut -d'.' -f 2))

        if [ -n "$original" ]
        then
            img_div="<a href=\"orig/${out}_o.$extension\"/><img alt=\"$title\" src=\"normal/${out}_n.$extension\"/></a>"
        else
            img_div="<img alt=\"$title\" src=\"normal/${out}_n.$extension\"/>"
        fi

        if [ -n "$exiv" ]
        then
            exiv_div=$(exiv_data "$file")
        fi

        if [ -n "$preceding" ]
        then
            preceding_div="<a id=\"prevLink\" rel=\"prev\" href=\"$preceding.html\">&larr;</a>"
            sed "s/##FOLLOWING_DIV##/<a id=\"nextLink\" rel=\"next\" href=\"$out.html\">\&rarr;<\/a>/g" "$output/$preceding.html" > $tmp
            cp $tmp "$output/$preceding.html"
        else
            preceding_div="&larr;"
        fi

        cat <<EOF>"$output/$out.html"
<html>
<head>
  <title>$title</title>
  <link rel="stylesheet" type="text/css" href="style.css">
  <link rel="shortcut icon" type="image/png" href="favicon.png">
</head>
<body>
  <script language=javascript type='text/javascript'>
     window.onload = function() {
       nextLink = document.getElementById("nextLink")
       prevLink = document.getElementById("prevLink")
       if(nextLink)
         nextURL = nextLink.href;
       else
         nextURL = "#";
       if(prevLink)
         prevURL = prevLink.href
       else
         prevURL = "#"

       document.onkeydown = function(event) {
       switch(event.keyCode) {
       case 37: /* left */
         window.location = prevURL;
         break;
       case 39: /* right */
         window.location = nextURL;
         break;
       }
      }
    };

    function toggle(id, defvalue) {
      var visibility = document.getElementById(id).style.visibility;
      if((visibility != "visible") && (visibility != "hidden"))
        document.getElementById(id).style.visibility = defvalue;
      else if(visibility == "visible")
        document.getElementById(id).style.visibility = "hidden";
      else
        document.getElementById(id).style.visibility = "visible";
    }
  </script>
  <center>
  <h1>$title</h1>
<p>
  <div id="nav">$preceding_div ##FOLLOWING_DIV## <a href="index.html">&#x2302;</a></div>
  <div id="photo">$img_div</div>
</p>

<div id="exif_switch" class="toggle"><a href="#" onclick="toggle('exif_switch', 'hidden');toggle('exif', 'visible');">Display EXIF informations</a></div>

<p>
  $exiv_div
</p>
</center>
</body>
</html>
EOF
        preceding="$out"
        echo "<div id=\"preview\"><a href=\"$out.html\"><img alt=\"[$title]\" src=\"tiny/${out}_t.$extension\"/></a>" >> "$index"
    done

done

sed "s/##FOLLOWING_DIV##/\&rarr;/g" "$output/$preceding.html" > $tmp
cp $tmp "$output/$preceding.html"

rm $tmp
cp $stylesheet $output/
echo "</div>" >> "$index"
echo "</center>" >> "$index"
echo "</body>" >> "$index"
echo "</html>" >> "$index"
